# Generated by Django 5.2.4 on 2025-07-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('dept', models.CharField(max_length=100)),
                ('sal', models.FloatField()),
            ],
        ),
    ]
